# Generated by Django 6.1.1 on 2026-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='         ', max_length=9)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('winner', models.CharField(blank=True, max_length=10, null=True)),
                ('game_mode', models.CharField(choices=[('pve_easy', 'Oson (Bot)'), ('pve_medium', "O'rtacha (Bot)"), ('pve_hard', 'Yengilmas (Minimax Bot)'), ('pvp', "2 O'yinchi (Do'st bilan)")], default='pve_hard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
